name: pull_request

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Branch or Commit ID (optional)'
        required: false
        type: string
  schedule:
    - cron: "0 12 * * *"

jobs:
  unit-tests:
    strategy:
      fail-fast: false # Don't cancel all on first failure
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo ${{ github.event_name == 'workflow_dispatch' && inputs.commit_id || github.sha }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.commit_id || github.sha }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Minimal install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Attempt import
        run: |
          python -c "import guidance"
      - name: Bigger install
        run: |
          pip install -e .[babytest]
      - name: Unit Tests
        run: |
          pytest -vv ./tests/unit
